### PR TITLE
fix(a11y): blur when tabbing out of input

### LINKED ISSUE #1926: Selectize element isFocused is true after $control_input gets blurred
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

After [this commit that fixes an issue with modals](https://github.com/selectize/selectize.js/commit/e5792126a839095e00a743a5bade38caabeac4e5#diff-42f49af8bfaecef45ea594811f65dcb9aade0fbd8d3e7246d50ee92e863297caR210) , selectize component has stopped tracking $control_input blur events, so it keeps the "isFocused" state even when it is not focused anymore. That causes some visual errors as long as some other issues

#### Issue 1: Selectize input doesn't loose focus styles when tabbing through inputs.
Steps to reproduce:

1. Go to Demo page https://selectize.dev/docs/demos/lock
2. Click on Bootstrap 5, in order to get focused styles around the input field
3. Click on first select input
4. Press tab key to navigate to next input.

Expected result:
First input looses focus styles while second input shows them

Actual result:
Both inputs show focus styles.

#### Issue 2: When clicking on the dropdown of a multiple select, input loses focus and it doesn't gain it back because `onFocus` callback checks if isFocused is true before setting it ( which it is ), so you can't search using the input
 Steps to reproduce:

1. Go to Demo page https://selectize.dev/docs/demos/opt-groups
2. Type "B" in the input
3. Select "Bolts" in the dropdown using the mouse click
6. Type "C"

Expected result:
I expect the input to be focused so when I type the "C" it search for an option and shows it in the dropdown.

Actual result:
When I type "C" nothing happens because the input is not focused. When I click on the input to focus it it doesn't gain focus either, so the only way I can use the search again is clicking away from the drowdown menu (close it) and focusing the input again.

### PR DESCRIPTION
**Pull request by meldafert**
Fixes #1926.
To be accessible, it should be possible to easily navigate elements using the keyboard.
Previously, when using TAB to navigate through form elements, the input would enter its focused state when focused with TAB (and the dropdown would open when using `openOnFocus`).
However, when TAB is used to jump to the next focusable element, it would not lose its focused state, and the dropdown would stay open. This commit restores the behavior before #1813 and ensures that the input leaves its focused state and closes the dropdown when blurred using TAB.

### CODE REVIEW

**Comment by meldafert** [comment]
This breaks a test apparently. I will make sure to fix this, and to add a test case using TAB.

**Comment by meldafert** [comment]
I have fixed the tests.
I also tried adding some tests for keyboard tabbing.
However, I was not able to get `syn.key()` to behave the way I want.
I emulated it using native `.focus()` for now, however that does not behave exactly the same way as actual keyboard tabbing, eg. for `selectOnTab`.
To get the best outcome, it would be necessary to use something like [puppeteer](https://www.npmjs.com/package/puppeteer-core) - this should be fairly easy as CI already has headless chrome set up.

File: src/selectize.js [hunk 1]
```diff
@@ -218,8 +218,8 @@ $.extend(Selectize.prototype, {
 			keypress  : function() { return self.onKeyPress.apply(self, arguments); },
 			input     : function() { return self.onInput.apply(self, arguments); },
 			resize    : function() { self.positionDropdown.apply(self, []); },
-			// blur      : function() { return self.onBlur.apply(self, arguments); },
-			focus     : function() { self.ignoreBlur = false; return self.onFocus.apply(self, arguments); },
```
Comment (meldafert) [inline src/selectize.js:222]: `ignoreBlur` was not read anywhere anymore. I removed the previous references and re-used it for detecting when an item in the dropdown was clicked, to avoid closing the dropdown in that case.

File: test/api.js [hunk 2]
```diff
@@ -633,7 +633,7 @@
 					test.selectize.search('hello');
 				}).to.not.throw(Error);
       });
-      it('should normalize a string', function () {
+      expect('should normalize a string', function () {
         var test;
 
         beforeEach(function() {
```
Comment (meldafert) [inline test/api.js:639]: This broke my new tests. Calling `beforeEach()` inside of `it()` (instead of inside `expect`) apparently applies it to all subsequent tests.

File: test/api.js [hunk 3]
```diff
@@ -642,11 +642,12 @@
...
         });
 
-        it('should return query satinized', function() {
+        it('should return query satinized', function(done) {
           var query = test.selectize.search('héllo').query;
 
           window.setTimeout(function () {
             expect(query).to.be.equal('hello');
+            done();
           }, 0);
```
Comment (meldafert) [inline test/api.js:651]: Drive-by fix to ensure the test terminates properly.

File: test/interaction.js [hunk 4]
```diff
@@ -413,6 +421,103 @@
...
+					expect(test.selectize.isOpen).to.be.equal(false);
+				});
+
+				// TODO: this would work if tabTo was using actual keyboard interactions,
+				// and not just focus()
+				xit('should select the first value on blur', async function() {
+					await tabTo(test.selectize.$control_input[0]);
+					await tabTo(input2[0]);
+					expect(test.selectize.getValue()).to.be.equal('a');
+				});
```
Comment (meldafert) [inline test/interaction.js:481]: This is the test that would require a better emulation/control over the headless browser (eg. puppeteer).

**Comment by risadams** [comment]
Kudos to you.  this is one of the best documented pull requests I've seen in a long time :)
Thanks!
